general {
    # الأمر اللي هيشغل hyprlock لما النظام يطلب قفل الشاشة
    lock_cmd = pidof hyprlock || hyprlock

    # قفل الشاشة فوراً قبل ما الجهاز يدخل في Sleep أو Hibernate
    before_sleep_cmd = loginctl lock-session

    # إضاءة الشاشة فوراً بعد ما الجهاز يصحى
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. تفعيل اللوك سكرين بعد دقيقة واحدة (60 ثانية) من عدم الاستخدام
listener {
    timeout = 60
    on-timeout = loginctl lock-session
}

# 2. إطفاء الشاشة بعد دقيقتين لتوفير الطاقة
listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
