-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

require("configs.colors")

-- Import split configuration files in the correct order
require("configs.monitors")
require("configs.programs")
require("configs.autostart")
require("configs.envs")
require("configs.permissions")
require("configs.look_and_feel")
require("configs.layouts")
require("configs.misc")
require("configs.input")
require("configs.keybindings")
require("configs.window_rules")
