general {
    no_fade_in = false
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    # لو مسار الكاش مش بيققرأ الصورة، بدله بمسار صورة خلفيتك المباشر (مثلاً /home/mazen/Pictures/wallpaper.png)
    path = $HOME/.config/hypr/wallpapers/.current
    
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

# 1. الكلمة المكتوبة (مثلاً Mazen's Setup)
label {
    monitor =
    text = Mazen's Setup
    color = rgba(240, 240, 240, 0.9)
    font_size = 28
    font_family = sans-serif
    position = 0, 50
    halign = center
    valign = center
}

# 2. الساعة الكبيرة
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    font_family = sans-serif
    position = 0, -20
    halign = center
    valign = center
}

# 3. خانة إدخال الباسورد (مخفية تماماً وشفافة 100% بدون أي بوكس أو حدود)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(0, 0, 0, 0)
    
    fade_on_empty = false
    placeholder_text = 
    hide_input = true
    
    position = 0, -120
    halign = center
    valign = center
}
