background #111318
foreground #e2e2e9
cursor #a9c7ff
cursor_text_color #09305f

selection_background #33353a
selection_foreground #e2e2e9

# الألوان القياسية (Normal Colors)
color0 #1d2024
color1 #ffb4ab
color2 #dcbce1
color3 #bdc7dc
color4 #a9c7ff
color5 #563e5c
color6 #3e4758
color7 #e2e2e9

# الألوان الساطعة (Bright Colors)
color8 #8e9099
color9 #ffb4ab
color10 #dcbce1
color11 #bdc7dc
color12 #a9c7ff
color13 #563e5c
color14 #3e4758
color15 #e2e2e9
